/*
  Guest list for the RSVP search — name + pase (party size) only.
  Phone numbers deliberately excluded: this file ships in the public
  site, and the couple chose speed over a private server-side lookup
  (see project memory). Source of truth is the Google Sheet in Drive;
  update both if the guest list changes.
*/
const GUESTS = [
  { name: "ADRIANA GASTELUM", pase: 1 },
  { name: "MARY VALDES", pase: 2 },
  { name: "ALESSANDRA BAZUA", pase: 2 },
  { name: "RUDY VALDES", pase: 2 },
  { name: "ALEXANDRA ELIAS", pase: 1 },
  { name: "VICTORIA VALDES", pase: 2 },
  { name: "ANA PAOLA MORENO", pase: 2 },
  { name: "ANASOL VALDES", pase: 1 },
  { name: "ANA SOFIA CASTRO", pase: 2 },
  { name: "ANA CECILIA VALDES", pase: 1 },
  { name: "CAROLINA TAMAYO", pase: 2 },
  { name: "ROBERTO VALDES", pase: 2 },
  { name: "CECILIA DOW", pase: 2 },
  { name: "VALERIA SADA", pase: 2 },
  { name: "DENISSE LELEVIER", pase: 2 },
  { name: "JAVIER SADA", pase: 1 },
  { name: "CARLOTA FONTES", pase: 1 },
  { name: "PAOLA ROMAN", pase: 1 },
  { name: "FERNANDA LEAL", pase: 1 },
  { name: "ANA LO VALDES", pase: 1 },
  { name: "PAOLA FRANCO", pase: 2 },
  { name: "ELENA VALDES", pase: 1 },
  { name: "FERNANDA HERNANDEZ", pase: 2 },
  { name: "RUDY MARTINEZ", pase: 1 },
  { name: "MELISSA JUAN", pase: 2 },
  { name: "VANESSA REILLY", pase: 1 },
  { name: "LARISSA LELEVIER", pase: 2 },
  { name: "THOMAS HUBKA", pase: 1 },
  { name: "MAURY TORRES", pase: 2 },
  { name: "SHANNON GALAMA", pase: 2 },
  { name: "FERNANDA PADILLA", pase: 2 },
  { name: "RT", pase: 1 },
  { name: "LUCIA PICO", pase: 2 },
  { name: "JANET HUBKA", pase: 2 },
  { name: "PAOLA CASTRO", pase: 2 },
  { name: "PEPE VALDES", pase: 4 },
  { name: "ARACELY YANEZ", pase: 2 },
  { name: "FERNANDA PEREZ SERNA", pase: 1 },
  { name: "JUAN CARLOS QUESADA", pase: 1 },
  { name: "JOSE MARIA IBARRA", pase: 1 },
  { name: "ROMINA LEON", pase: 1 },
  { name: "GABRIELA TAPIA", pase: 1 },
  { name: "MARIANNA ACOSTA", pase: 2 },
  { name: "JOHANNA ARELLANO", pase: 2 },
  { name: "SILVIA ARELLANO", pase: 1 },
  { name: "JULIANA VALDES", pase: 2 },
  { name: "BARBARA", pase: 2 },
  { name: "VITTORIO", pase: 2 },
  { name: "DORA", pase: 5 },
  { name: "AGNESE", pase: 2 },
  { name: "CHIARA", pase: 2 },
  { name: "BEATRICE", pase: 1 },
  { name: "MICHELLE URETA", pase: 1 },
  { name: "CARLOS HECTOR", pase: 1 },
  { name: "FIDEL RUIZ", pase: 1 },
  { name: "GUILLERMO PRIETO", pase: 2 },
  { name: "NORMA GAXIOLA", pase: 2 },
  { name: "JORGE RITZ", pase: 1 },
];
